### ISSUE TITLE
**Cards**

### ISSUE THREAD

**Issue by caitlinconsults** [caitlinconsults/Springboard-capstone#1]
What happens if I change a note?
[Uploading ShippingLabel (2).pdf…](This is a PDF)

**Comment by caitlinrdavies** [comment]
What happens if I leave a comment

**Comment by caitlinrdavies** [comment]
[ShippingLabel (2).pdf](https://github.com/caitlinrdavies/Springboard-capstone/files/4724206/ShippingLabel.2.pdf)
